### ISSUE TITLE
Data file missing in the RDF2Vec Training - DB_KEGG_PGK Data.ipynb

### ISSUE THREAD

**Issue by rezacsedu** [rcelebi/GraphEmbedding4DDI#1]
Hi @rcelebi,

I was trying to reproduce the result you reported in the SWAT4LS'2018 paper. However, it seems some data files are missing.

To be more specific, the following files used in 'RDF2Vec Training - DB_KEGG_PGK Data.ipynb' notebook are missing: 

-- entity2id.txt
-- relation2id.txt

I was wondering to get these files? 

Kind regards,
Karim

**Comment by rcelebi** [comment]
Hi Karim,
Please refer to the following notebook file for full pipeline of RDF2Vec embedding generation:
https://github.com/rcelebi/GraphEmbedding4DDI/blob/master/RDF2Vec%2BPipeline-Drug%2BRep-Vector-Bio-Drugbank%20KB.ipynb
You will need the Drugbank Knowledge Graph, it can be dowloaded from: http://download.bio2rdf.org/files/release/4/drugbank/drugbank.nq.gz
Let me know if you encounter any issue.
Note: The code requires Spark to be installed.
Cheers,
Remzi

**Comment by rezacsedu** [comment]
@rcelebi, thanks a million. I'll follow your instructions.

**Comment by XuanLin1991** [comment]
Hi, I was trying to generate a new knowledge graph by myself, and how to generate such a compressed file (e.g., http://download.bio2rdf.org/files/release/4/drugbank/drugbank.nq.gz)

Kind regards,
Xuan

**Comment by rcelebi** [comment]
Hi Xuan,
If you want to generate bio2rdf knowledge graphs (KGs), you can use our library: https://github.com/MaastrichtU-IDS/bio2rdf
This library can be also used to generate any other KGs. Note that you need to define mappings to convert your data from generic RDF to your target ontology. Please let us know if you have any issue with conversion.
Thanks

**Comment by XuanLin1991** [comment]
@rcelebi Thank you for your quick reply. I will try what you said. And by the way, is there any citation about your paper on DDI if  I want to cite later?  Have a good day!

**Comment by rcelebi** [comment]
Hi, 
yes, sure. To cite our paper:
Celebi, Remzi, Erkan Yasar, Huseyin Uyar, Ozgur Gumus, Oguz Dikenelli, and Michel Dumontier. "Evaluation of Knowledge Graph Embedding Approaches for Drug-Drug Interaction Prediction using Linked Open Data.", Proceedings of the 11th International Conference Semantic Web Applications and Tools for Life Sciences (SWAT4HCLS 2018), CEUR-WS.org,  2018.

Have a good day too!
