### ISSUE TITLE
RDF2Vec without Spark

### ISSUE THREAD

**Issue by Lemour-sudo** [rcelebi/GraphEmbedding4DDI#3]
Can you kindly share advice on how to implement RDF2Vec without pyspark. Thank you.

**Comment by rcelebi** [comment]
I added a simple RDF2Vec implementation without using Spark. Here is [the link](https://github.com/rcelebi/GraphEmbedding4DDI/blob/master/RDF2Vec%2BPipeline-Without-Spark.ipynb) 

If you need more features, you might want to use this library for RDF2Vec: [pyRDF2Vec](https://github.com/IBCNServices/pyRDF2Vec)

**Comment by Lemour-sudo** [comment]
Thank you.
