### ISSUE TITLE
The file of labeled_ddi_DBv5.0.3.csv

### ISSUE THREAD

**Issue by huluoboli** [rcelebi/GraphEmbedding4DDI#4]
Hi @rcelebi,

    I want to know the usefulness of the labeled_ddi_DBv5.0.3.csv file. Does the corresponding label id refer to the relationship between the two drugs? Can you provide a specific relationship corresponding to the label ID? Thank you!

**Comment by rcelebi** [comment]
Hi @huluoboli,
Sorry for the late response. This data comes from the study 'Deep learning improves prediction of drug–drug and drug–food interactions' by Ryu JY, Kim HU, Lee SY. Labels are types that were extracted from DrugBank DDI definitions using sentence structures, and these types can give an indication about the mechanisms of DDIs. You can refer to the study for more information.
There is a notebook showing how I retrieved this data: [the link](https://github.com/rcelebi/GraphEmbedding4DDI/blob/master/plots/distribution%20DDI%20types.ipynb)

**Comment by huluoboli** [comment]
Thank you.
